name: CI

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test-auth:
    needs: build
    uses: ./.github/workflows/test-auth.yml
    secrets: inherit

  test-venues:
    needs: build
    uses: ./.github/workflows/test-venues.yml
    secrets: inherit

  test-ap-groups:
    needs: build
    uses: ./.github/workflows/test-ap-groups.yml
    secrets: inherit

  test-aps:
    needs: build
    uses: ./.github/workflows/test-aps.yml
    secrets: inherit

  test-directory-server:
    needs: build
    uses: ./.github/workflows/test-directory-server.yml
    secrets: inherit

  test-radius-server:
    needs: build
    uses: ./.github/workflows/test-radius-server.yml
    secrets: inherit

  test-portal-service:
    needs: build
    uses: ./.github/workflows/test-portal-service.yml
    secrets: inherit

  test-roles:
    needs: build
    uses: ./.github/workflows/test-roles.yml
    secrets: inherit

  test-wifi-networks:
    needs: build
    uses: ./.github/workflows/test-wifi-networks.yml
    secrets: inherit

  test-guest-passes:
    needs: build
    uses: ./.github/workflows/test-guest-passes.yml
    secrets: inherit

  test-clients:
    needs: build
    uses: ./.github/workflows/test-clients.yml
    secrets: inherit
